version: '3'
services:
  users-service:
    build: ./service
    container_name: users_service
    ports:
     - "8123:8123"
    links:
      - db:db
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./database
